# Book settings
title: Learning Statistics with Python
author: Danielle Navarro (bookdown - Emily Kothe, jupyter-book - Gavin Cooper)

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: force
  exclude_patterns:
    - 'Untitled*'

# sphinx:
#   extensions:
#     - myst_nb
