# Book settings
title: Learning Statistics with Python
author: Danielle Navarro (bookdown - Emily Kothe, jupyter-book - Gavin Cooper)
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: force
